#!/bin/sh

: "${SUDO_UID:?Ошибка: Переменная SUDO_UID пуста или не задана!}"

NAMESPACE=$(cat -- resourcepack_namespace) || { echo "Ошибка: не удалось прочитать файл namespace!" >&2; exit 1; }
UUID=$(uuidgen --sha1 -n "$NAMESPACE" -N "$SUDO_UID") || { echo "Ошибка: не удалось сгенерировать UUID" >&2; exit 1;}
printf '%s' "$UUID"

FILE_PATH="out/$UUID"

cp --reflink=always /dev/stdin "$FILE_PATH" || { echo "Ошибка: не удалось скопировать файл" >&2; exit 1;}
